import type { AdPlacementFormInput } from "@/types/ads";

export const EMPTY_AD_PLACEMENT_FORM: AdPlacementFormInput = {
  placement_key: "",
  name: "",
  description: "",
  surface: "chapter_reader",
  page_pattern: "",
  device: "mobile",
  position: "bottom",
  ad_format: "display",
  size_mode: "responsive",
  is_enabled: false,
  is_test_mode: true,
  priority: 100,
  max_per_page: 1,
  min_content_gap: 0,
  max_ads_per_chapter: 2,
  min_paragraphs_before: 0,
  min_paragraphs_after: 0,
  min_distance_px: 800,
  show_label: true,
  lazy_load: true,
  reserve_space: true,
  sticky_allowed: false,
  hide_for_vip: false,
  hide_for_owner: true,
  hide_on_sensitive_content: true,
  no_ads_respect: true,
  full_width_responsive: true,
  revenue_eligible: false,
  attribution_mode: "platform_only",
  revenue_bucket: "reader_ads"
};

export function rowToForm(row: import("@/types/ads").AdPlacementRow): AdPlacementFormInput {
  return {
    placement_key: row.placement_key,
    name: row.name,
    description: row.description,
    surface: row.surface,
    page_pattern: row.page_pattern,
    device: row.device,
    position: row.position,
    ad_format: row.ad_format,
    size_mode: row.size_mode,
    width: row.width,
    height: row.height,
    max_width: row.max_width,
    min_height: row.min_height,
    adsense_slot_id: row.adsense_slot_id,
    adsense_client_id: row.adsense_client_id,
    is_enabled: row.is_enabled,
    is_test_mode: row.is_test_mode,
    priority: row.priority,
    max_per_page: row.max_per_page,
    min_content_gap: row.min_content_gap,
    max_ads_per_chapter: row.max_ads_per_chapter,
    min_paragraphs_before: row.min_paragraphs_before,
    min_paragraphs_after: row.min_paragraphs_after,
    min_distance_px: row.min_distance_px,
    feed_cooldown_items: row.feed_cooldown_items,
    show_label: row.show_label,
    lazy_load: row.lazy_load,
    reserve_space: row.reserve_space,
    sticky_allowed: row.sticky_allowed,
    hide_for_vip: row.hide_for_vip,
    hide_for_owner: row.hide_for_owner,
    hide_on_sensitive_content: row.hide_on_sensitive_content,
    no_ads_respect: row.no_ads_respect,
    full_width_responsive: row.full_width_responsive,
    fallback_text: row.fallback_text,
    revenue_eligible: row.revenue_eligible,
    attribution_mode: row.attribution_mode,
    revenue_bucket: row.revenue_bucket,
    notes: row.notes,
    internal_note: row.internal_note
  };
}
