import { slugify } from "@/lib/slugify";
import { parentSlugForSubgenreName } from "@/lib/taxonomy/seed/subgenre-parents";
import type { TaxonomyType } from "@/types/taxonomy";

export type TaxonomySeedTerm = {
  type: TaxonomyType;
  slug: string;
  name: string;
  parentSlug?: string;
  sortOrder?: number;
  isSelectableByCreator?: boolean;
  isPublic?: boolean;
  isActive?: boolean;
  isFeatured?: boolean;
  useForModeration?: boolean;
  aliases?: string[];
  displayLabel?: string;
};

function fromNames(
  type: TaxonomyType,
  names: string[],
  options?: {
    startOrder?: number;
    isSelectableByCreator?: boolean;
    slugOverrides?: Record<string, string>;
  }
): TaxonomySeedTerm[] {
  const start = options?.startOrder ?? 0;
  return names.map((name, index) => ({
    type,
    name,
    slug: options?.slugOverrides?.[name] ?? slugify(name),
    sortOrder: start + index + 1,
    isSelectableByCreator: options?.isSelectableByCreator
  }));
}

function fromSlugs(
  type: TaxonomyType,
  entries: Array<{ slug: string; name: string }>,
  options?: { isSelectableByCreator?: boolean; startOrder?: number }
): TaxonomySeedTerm[] {
  const start = options?.startOrder ?? 0;
  return entries.map((entry, index) => ({
    type,
    slug: entry.slug,
    name: entry.name,
    sortOrder: start + index + 1,
    isSelectableByCreator: options?.isSelectableByCreator
  }));
}

function fromSubgenreNames(names: string[]): TaxonomySeedTerm[] {
  return names.map((name, index) => ({
    type: "subgenre" as const,
    name,
    slug: slugify(name),
    sortOrder: index + 1,
    parentSlug: parentSlugForSubgenreName(name)
  }));
}

const CREATOR_STATUS_PUBLIC = fromSlugs("story_status", [
  { slug: "ongoing", name: "Đang ra" },
  { slug: "completed", name: "Hoàn thành" },
  { slug: "hiatus", name: "Tạm ngưng" },
  { slug: "upcoming", name: "Sắp ra mắt" }
]);

const CREATOR_STATUS_INTERNAL = fromSlugs(
  "story_status",
  [
    { slug: "locked", name: "Đã khóa" },
    { slug: "hidden", name: "Đã ẩn" },
    { slug: "under_review", name: "Đang kiểm duyệt" },
    { slug: "needs_revision", name: "Cần chỉnh sửa" },
    { slug: "low_quality", name: "Nội dung thấp" },
    { slug: "not_monetized", name: "Không kiếm tiền" },
    { slug: "free_access", name: "Miễn phí" },
    { slug: "paid_access", name: "Trả phí" },
    { slug: "bundle_sale", name: "Bán trọn bộ" },
    { slug: "has_new_chapter", name: "Có chương mới" }
  ],
  { isSelectableByCreator: false, startOrder: CREATOR_STATUS_PUBLIC.length }
);

export const DEFAULT_TAXONOMY_SEED_TERMS: TaxonomySeedTerm[] = [
  ...fromNames("content_type", [
    "Truyện dài",
    "Truyện ngắn",
    "Truyện nhiều chương",
    "Truyện một chương",
    "Series truyện ngắn",
    "Tiểu thuyết web",
    "Đoạn văn",
    "Tản văn",
    "Nhật ký hư cấu",
    "Thơ",
    "Kịch bản hội thoại",
    "Chat story",
    "Truyện dạng tin nhắn",
    "Truyện tương tác",
    "Truyện lựa chọn nhánh",
    "Reels truyện",
    "Bài viết",
    "Thông báo",
    "Hướng dẫn viết truyện",
    "Review / cảm nhận truyện"
  ]),
  ...fromNames("main_genre", [
    "Ngôn tình",
    "Lãng mạn",
    "Đô thị",
    "Thanh xuân",
    "Học đường",
    "Gia đình",
    "Tâm lý",
    "Đời thường",
    "Hài hước",
    "Drama",
    "Hành động",
    "Phiêu lưu",
    "Trinh thám",
    "Hình sự",
    "Kinh dị",
    "Tâm linh",
    "Huyền bí",
    "Giả tưởng",
    "Fantasy",
    "Tiên hiệp",
    "Kiếm hiệp",
    "Huyền huyễn",
    "Tu tiên",
    "Xuyên không",
    "Trọng sinh",
    "Dị giới",
    "Isekai",
    "Khoa học viễn tưởng",
    "Cyberpunk",
    "Hậu tận thế",
    "Sinh tồn",
    "Game / hệ thống",
    "LitRPG",
    "Võng du",
    "Lịch sử",
    "Cổ đại",
    "Cung đấu",
    "Quan trường",
    "Quân sự",
    "Chiến tranh",
    "Đam mỹ",
    "Bách hợp",
    "Fanfiction",
    "Thiếu nhi",
    "Tuổi teen",
    "Chữa lành",
    "Truyền cảm hứng",
    "Châm biếm",
    "Siêu nhiên",
    "Siêu anh hùng",
    "Thể thao",
    "Âm nhạc / showbiz",
    "Nghề nghiệp",
    "Kinh doanh",
    "Y khoa",
    "Pháp luật",
    "Ẩm thực",
    "Du lịch"
  ]),
  ...fromSubgenreNames([
    "Ngọt sủng",
    "Ngược tâm",
    "Ngược thân",
    "Cưới trước yêu sau",
    "Yêu thầm",
    "Gương vỡ lại lành",
    "Tình đầu",
    "Tình yêu trưởng thành",
    "Tình yêu công sở",
    "Tổng tài",
    "Hào môn",
    "Hợp đồng hôn nhân",
    "Bạn thân thành người yêu",
    "Kẻ thù thành người yêu",
    "Tình yêu chữa lành",
    "Công sở",
    "Khởi nghiệp",
    "Gia đình",
    "Hôn nhân",
    "Ly hôn",
    "Nuôi con",
    "Làng quê",
    "Đời sống thành thị",
    "Giới giải trí",
    "Livestream / mạng xã hội",
    "Báo chí",
    "Y tế",
    "Luật pháp",
    "Kinh doanh",
    "Đời học sinh",
    "Đời sinh viên",
    "Phép thuật",
    "Rồng",
    "Ma pháp học viện",
    "Thần thoại",
    "Quỷ tộc",
    "Thiên thần",
    "Ác ma",
    "Quái vật",
    "Dị năng",
    "Linh khí",
    "Khế ước",
    "Triệu hồi",
    "Vương quốc",
    "Đế chế",
    "Luyện khí",
    "Trúc cơ",
    "Kim đan",
    "Nguyên anh",
    "Phi thăng",
    "Tông môn",
    "Ma đạo",
    "Chính đạo",
    "Linh thú",
    "Đan dược",
    "Trận pháp",
    "Bí cảnh",
    "Hệ thống nhiệm vụ",
    "Level up",
    "Thanh trạng thái",
    "Kỹ năng",
    "Hầm ngục",
    "Boss",
    "Bang hội",
    "Võng du thực tế ảo",
    "Game sinh tồn",
    "Game kinh dị",
    "Ma quỷ",
    "Ám ảnh",
    "Nhà hoang",
    "Trường học ma ám",
    "Nghi lễ",
    "Lời nguyền",
    "Đô thị truyền thuyết",
    "Tâm linh Việt Nam",
    "Phá án",
    "Serial killer",
    "Điều tra tâm lý",
    "Hồ sơ tội phạm",
    "Thám tử tư",
    "Cảnh sát",
    "Pháp y",
    "Du hành thời gian",
    "Không gian vũ trụ",
    "Robot",
    "AI hư cấu",
    "Cyborg",
    "Thực tại ảo",
    "Đa vũ trụ",
    "Dịch bệnh",
    "Xã hội tương lai",
    "Zombie",
    "Thiên tai",
    "Thế giới sụp đổ",
    "Sinh tồn nhóm",
    "Căn cứ"
  ]),
  ...fromNames("trope_tag", [
    "Từ yếu thành mạnh",
    "Báo thù",
    "Ẩn danh cao thủ",
    "Giả nghèo",
    "Đổi đời",
    "Lật mặt",
    "Bị phản bội",
    "Quay về quá khứ",
    "Biết trước tương lai",
    "Mang ký ức kiếp trước",
    "Có hệ thống",
    "Có không gian riêng",
    "Có năng lực đặc biệt",
    "Thân phận bí mật",
    "Con rơi hào môn",
    "Thiên tài bị xem thường",
    "Phế vật nghịch tập",
    "Sống lại lần nữa",
    "Xuyên vào truyện",
    "Xuyên vào game",
    "Xuyên thành phản diện",
    "Xuyên thành nhân vật phụ",
    "Cứu rỗi lẫn nhau",
    "Tự lập làm giàu",
    "Từ hôn",
    "Vả mặt",
    "Cạnh tranh gia tộc",
    "Đấu trí",
    "Sinh tồn",
    "Giải mã bí ẩn",
    "Tìm lại ký ức",
    "Truy tìm hung thủ",
    "Chạy trốn",
    "Bị mắc kẹt",
    "Lựa chọn sinh tử",
    "Thế giới giả lập"
  ]),
  ...fromNames("setting_tag", [
    "Việt Nam hiện đại",
    "Sài Gòn",
    "Hà Nội",
    "Miền Tây",
    "Miền Trung",
    "Làng quê Việt",
    "Trường học",
    "Đại học",
    "Công sở",
    "Bệnh viện",
    "Tòa án",
    "Đồn cảnh sát",
    "Showbiz",
    "Hào môn",
    "Giới kinh doanh",
    "Cung đình",
    "Triều đại giả tưởng",
    "Trung Hoa cổ đại",
    "Châu Âu trung cổ",
    "Thế giới phép thuật",
    "Dị giới",
    "Thế giới game",
    "Không gian vũ trụ",
    "Tương lai gần",
    "Hậu tận thế",
    "Đảo hoang",
    "Tàu biển",
    "Núi rừng",
    "Nhà hoang",
    "Ký túc xá",
    "Chung cư",
    "Quán cà phê",
    "Hiệu sách"
  ]),
  ...fromNames("character_tag", [
    "Nam chính mạnh",
    "Nữ chính mạnh",
    "Nam chính lạnh lùng",
    "Nữ chính cá tính",
    "Nam chính dịu dàng",
    "Nữ chính thông minh",
    "Phản diện có chiều sâu",
    "Anti-hero",
    "Thiên tài",
    "Người bình thường",
    "Người chữa lành",
    "Kẻ báo thù",
    "Cảnh sát",
    "Thám tử",
    "Luật sư",
    "Bác sĩ",
    "Tổng tài",
    "Nghệ sĩ",
    "Streamer",
    "Nhà văn",
    "Học sinh",
    "Sinh viên",
    "Giáo viên",
    "Sát thủ",
    "Tu sĩ",
    "Pháp sư",
    "Chiến binh",
    "Quái vật",
    "Ma",
    "Robot",
    "AI hư cấu",
    "Nhân vật mất trí nhớ",
    "Nhân vật có bí mật",
    "Nhân vật tổn thương"
  ]),
  ...fromNames("relationship_tag", [
    "Không có tuyến tình cảm",
    "Tình cảm nhẹ",
    "Romance chính",
    "Romance phụ",
    "Tình yêu chậm nhiệt",
    "Yêu thầm",
    "Bạn bè thành yêu",
    "Kẻ thù thành yêu",
    "Cưới trước yêu sau",
    "Hợp đồng tình yêu",
    "Tình yêu công sở",
    "Tình yêu học đường",
    "Tình yêu trưởng thành",
    "Gia đình",
    "Tình cha con",
    "Tình mẹ con",
    "Anh em",
    "Tình bạn",
    "Sư đồ",
    "Đồng đội",
    "Đối thủ",
    "Chủ tớ",
    "Oan gia",
    "Tam giác tình yêu"
  ]),
  ...fromNames("narrative_style", [
    "Ngôi thứ nhất",
    "Ngôi thứ ba",
    "Nhiều góc nhìn",
    "Một góc nhìn",
    "Góc nhìn nam chính",
    "Góc nhìn nữ chính",
    "Góc nhìn phản diện",
    "Kể tuyến tính",
    "Kể phi tuyến",
    "Đan xen quá khứ hiện tại",
    "Nhật ký",
    "Thư từ",
    "Hồ sơ vụ án",
    "Dạng phỏng vấn",
    "Dạng tin nhắn",
    "Dạng bài đăng mạng xã hội",
    "Dạng ghi âm / transcript",
    "Dạng kịch bản",
    "Dạng nhiệm vụ hệ thống"
  ]),
  ...fromSlugs("presentation_mode", [
    { slug: "standard_prose", name: "Văn xuôi truyền thống" },
    { slug: "chat_story", name: "Chat story / tin nhắn" },
    { slug: "social_feed", name: "Bài đăng mạng xã hội giả lập" },
    { slug: "case_file", name: "Hồ sơ vụ án / điều tra" },
    { slug: "diary", name: "Nhật ký nhân vật" },
    { slug: "system_game", name: "Giao diện hệ thống / game" },
    { slug: "script", name: "Kịch bản thoại" },
    { slug: "mixed_media", name: "Trình bày hỗn hợp" }
  ]),
  ...fromNames("reader_experience", [
    "Nhẹ nhàng",
    "Chữa lành",
    "Căng thẳng",
    "Hồi hộp",
    "Đen tối",
    "Buồn",
    "Ấm áp",
    "Hài hước",
    "Dễ thương",
    "Kịch tính",
    "Ám ảnh",
    "Sâu sắc",
    "Nhanh gọn",
    "Đọc thư giãn",
    "Plot twist nhiều",
    "Drama cao",
    "Slow burn",
    "Fast-paced",
    "Não to",
    "Cảm động"
  ]),
  ...fromNames("content_warning", [
    "Ngôn từ mạnh",
    "Bạo lực nhẹ",
    "Bạo lực nặng",
    "Máu me",
    "Kinh dị",
    "Tâm lý nặng",
    "Tự hại / tự tử",
    "Bắt nạt",
    "Lạm dụng",
    "Ám ảnh tâm lý",
    "Cái chết nhân vật",
    "Tai nạn",
    "Chiến tranh",
    "Phân biệt đối xử",
    "Nội dung người lớn",
    "Tình dục gợi ý",
    "Tình dục rõ ràng",
    "Chất kích thích",
    "Cờ bạc",
    "Tội phạm",
    "Bạo lực gia đình",
    "Cưỡng ép / không đồng thuận"
  ]),
  ...fromSlugs("age_rating", [
    { slug: "all_ages", name: "Mọi lứa tuổi" },
    { slug: "teen_13", name: "13+" },
    { slug: "young_adult_16", name: "16+" },
    { slug: "mature_18", name: "18+" },
    { slug: "unrated", name: "Chưa phân loại" }
  ]),
  ...CREATOR_STATUS_PUBLIC,
  ...CREATOR_STATUS_INTERNAL,
  ...fromSlugs(
    "monetization_access",
    [
      { slug: "free_all", name: "Miễn phí toàn bộ" },
      { slug: "free_preview", name: "Miễn phí chương đầu" },
      { slug: "paid_from_chapter", name: "Trả phí từ chương X" },
      { slug: "paid_per_chapter", name: "Trả phí từng chương" },
      { slug: "bundle_sale", name: "Bán trọn bộ" },
      { slug: "vip_chapter", name: "Chương VIP" },
      { slug: "coin_locked_chapter", name: "Chương khóa Coin" },
      { slug: "revenue_paused", name: "Tạm khóa doanh thu" },
      { slug: "not_eligible_monetization", name: "Không đủ điều kiện kiếm tiền" }
    ],
    { isSelectableByCreator: false }
  ),
  ...fromSlugs(
    "editorial_tag",
    [
      { slug: "recommended", name: "Đề xuất" },
      { slug: "featured", name: "Nổi bật" },
      { slug: "trending", name: "Đang lên" },
      { slug: "new_author", name: "Tác giả mới" },
      { slug: "new_story_highlight", name: "Truyện mới đáng chú ý" },
      { slug: "long_tail_quality", name: "Long-tail chất lượng" },
      { slug: "high_continue_reading", name: "Đọc tiếp cao" },
      { slug: "high_completion_rate", name: "Tỷ lệ hoàn thành tốt" },
      { slug: "frequently_reported", name: "Bị báo cáo nhiều" },
      { slug: "needs_better_opening", name: "Cần cải thiện mở đầu" },
      { slug: "needs_better_description", name: "Cần cải thiện mô tả" },
      { slug: "missing_cover", name: "Thiếu ảnh" },
      { slug: "missing_tags", name: "Thiếu tag" },
      { slug: "wrong_tags", name: "Tag sai" },
      { slug: "low_quality_content", name: "Nội dung thấp" }
    ],
    { isSelectableByCreator: false }
  )
].map((term) => ({
  ...term,
  isSelectableByCreator:
    term.isSelectableByCreator ??
    !["editorial_tag", "monetization_access"].includes(term.type),
  isPublic: term.isPublic ?? true,
  isActive: term.isActive ?? true,
  isFeatured: term.isFeatured ?? false,
  useForModeration: term.useForModeration ?? term.type === "editorial_tag"
}));

export const DEFAULT_STORY_FORMAT_TEMPLATE_SEEDS = [
  {
    mode: "standard_prose",
    name: "Văn xuôi mặc định",
    description: "Chương văn xuôi truyền thống.",
    isDefault: true,
    sortOrder: 1
  },
  {
    mode: "chat_story",
    name: "Chat story cơ bản",
    description: "Tin nhắn xen kẽ đối thoại.",
    isDefault: true,
    sortOrder: 1
  },
  {
    mode: "case_file",
    name: "Hồ sơ vụ án",
    description: "Ghi chép điều tra, báo cáo, transcript.",
    isDefault: true,
    sortOrder: 1
  }
] as const;
