-- Taxonomy: subgenre parent links + ranking_snapshots.taxonomy_term_id

alter table public.ranking_snapshots
  add column if not exists taxonomy_term_id uuid
  references public.taxonomy_terms(id) on delete set null;

create index if not exists ranking_snapshots_taxonomy_term_idx
  on public.ranking_snapshots (taxonomy_term_id, snapshot_at desc)
  where taxonomy_term_id is not null;

-- Link subgenres to main_genre (idempotent; safe after 161 seed)
update public.taxonomy_terms child
set
  parent_id = parent.id,
  updated_at = now()
from public.taxonomy_terms parent
where child.type = 'subgenre'
  and parent.type = 'main_genre'
  and child.parent_id is null
  and parent.slug = case child.slug
    when 'ngot-sung' then 'ngon-tinh'
    when 'nguoc-tam' then 'ngon-tinh'
    when 'nguoc-than' then 'ngon-tinh'
    when 'cuoi-truoc-yeu-sau' then 'ngon-tinh'
    when 'yeu-tham' then 'ngon-tinh'
    when 'guong-vo-lai-lanh' then 'ngon-tinh'
    when 'tinh-dau' then 'ngon-tinh'
    when 'tinh-yeu-truong-thanh' then 'ngon-tinh'
    when 'tinh-yeu-cong-so' then 'ngon-tinh'
    when 'hop-dong-hon-nhan' then 'ngon-tinh'
    when 'ban-than-thanh-nguoi-yeu' then 'ngon-tinh'
    when 'ke-thu-thanh-nguoi-yeu' then 'ngon-tinh'
    when 'tinh-yeu-chua-lanh' then 'ngon-tinh'
    when 'hon-nhan' then 'ngon-tinh'
    when 'ly-hon' then 'ngon-tinh'
    when 'tong-tai' then 'do-thi'
    when 'hao-mon' then 'do-thi'
    when 'cong-so' then 'do-thi'
    when 'khoi-nghiep' then 'do-thi'
    when 'kinh-doanh' then 'do-thi'
    when 'gioi-giai-tri' then 'do-thi'
    when 'livestream-mang-xa-hoi' then 'do-thi'
    when 'bao-chi' then 'do-thi'
    when 'gia-dinh' then 'gia-dinh'
    when 'nuoi-con' then 'gia-dinh'
    when 'lang-que' then 'doi-thuong'
    when 'doi-song-thanh-thi' then 'doi-thuong'
    when 'doi-hoc-sinh' then 'hoc-duong'
    when 'doi-sinh-vien' then 'hoc-duong'
    when 'luyen-khi' then 'tu-tien'
    when 'truc-co' then 'tu-tien'
    when 'kim-dan' then 'tu-tien'
    when 'nguyen-anh' then 'tu-tien'
    when 'phi-thang' then 'tu-tien'
    when 'linh-khi' then 'tu-tien'
    when 'dan-duoc' then 'tu-tien'
    when 'tran-phap' then 'tu-tien'
    when 'bi-canh' then 'tu-tien'
    when 'tong-mon' then 'kiem-hiep'
    when 'ma-dao' then 'kiem-hiep'
    when 'chinh-dao' then 'kiem-hiep'
    when 'linh-thu' then 'kiem-hiep'
    when 'phep-thuat' then 'fantasy'
    when 'rong' then 'fantasy'
    when 'ma-phap-hoc-vien' then 'fantasy'
    when 'than-thoai' then 'fantasy'
    when 'quy-toc' then 'fantasy'
    when 'thien-than' then 'fantasy'
    when 'ac-ma' then 'fantasy'
    when 'quai-vat' then 'fantasy'
    when 'di-nang' then 'fantasy'
    when 'khe-uoc' then 'fantasy'
    when 'trieu-hoi' then 'fantasy'
    when 'vuong-quoc' then 'lich-su'
    when 'de-che' then 'lich-su'
    when 'he-thong-nhiem-vu' then 'game-he-thong'
    when 'level-up' then 'game-he-thong'
    when 'thanh-trang-thai' then 'game-he-thong'
    when 'ky-nang' then 'game-he-thong'
    when 'ham-nguc' then 'game-he-thong'
    when 'boss' then 'game-he-thong'
    when 'bang-hoi' then 'game-he-thong'
    when 'vong-du-thuc-te-ao' then 'game-he-thong'
    when 'game-sinh-ton' then 'game-he-thong'
    when 'game-kinh-di' then 'game-he-thong'
    when 'ma-quy' then 'kinh-di'
    when 'am-anh' then 'kinh-di'
    when 'nha-hoang' then 'kinh-di'
    when 'truong-hoc-ma-am' then 'kinh-di'
    when 'nghi-le' then 'kinh-di'
    when 'loi-nguyen' then 'kinh-di'
    when 'do-thi-truyen-thuyet' then 'kinh-di'
    when 'tam-linh-viet-nam' then 'tam-linh'
    when 'pha-an' then 'trinh-tham'
    when 'serial-killer' then 'trinh-tham'
    when 'dieu-tra-tam-ly' then 'trinh-tham'
    when 'ho-so-toi-pham' then 'trinh-tham'
    when 'tham-tu-tu' then 'trinh-tham'
    when 'canh-sat' then 'trinh-tham'
    when 'phap-y' then 'trinh-tham'
    when 'du-hanh-thoi-gian' then 'khoa-hoc-vien-tuong'
    when 'khong-gian-vu-tru' then 'khoa-hoc-vien-tuong'
    when 'robot' then 'khoa-hoc-vien-tuong'
    when 'ai-hu-cau' then 'khoa-hoc-vien-tuong'
    when 'cyborg' then 'khoa-hoc-vien-tuong'
    when 'thuc-te-ao' then 'khoa-hoc-vien-tuong'
    when 'da-vu-tru' then 'khoa-hoc-vien-tuong'
    when 'xa-hoi-tuong-lai' then 'khoa-hoc-vien-tuong'
    when 'dich-benh' then 'sinh-ton'
    when 'thien-tai' then 'sinh-ton'
    when 'the-gioi-sup-do' then 'sinh-ton'
    when 'sinh-ton-nhom' then 'sinh-ton'
    when 'can-cu' then 'sinh-ton'
    when 'zombie' then 'sinh-ton'
    when 'y-te' then 'y-khoa'
    when 'luat-phap' then 'phap-luat'
    else null
  end
  and parent.slug is not null;
