-- Reader desktop skyscraper rails (left / right of chapter layout)

insert into public.ad_placements (
  placement_key,
  name,
  description,
  surface,
  page_pattern,
  device,
  position,
  ad_format,
  size_mode,
  width,
  height,
  max_width,
  min_height,
  is_enabled,
  is_test_mode,
  max_per_page,
  min_content_gap,
  sticky_allowed,
  revenue_eligible,
  revenue_bucket,
  notes
)
values
  (
    'desktop_reader_left_rail',
    'Rail trái đọc chương (desktop)',
    'Skyscraper / display dọc mép trái màn hình khi đọc chương. Khuyến nghị 160×600 hoặc responsive hẹp (~120–160px).',
    'chapter_reader',
    '/truyen/*/chuong/*',
    'desktop',
    'sidebar',
    'display',
    'responsive',
    160,
    600,
    160,
    600,
    false,
    true,
    1,
    0,
    true,
    true,
    'reader_ads',
    'Hiển thị từ xl (≥1280px), sticky khi cuộn.'
  ),
  (
    'desktop_reader_right_rail',
    'Rail phải đọc chương (desktop)',
    'Skyscraper / display dọc mép phải màn hình khi đọc chương. Khuyến nghị 160×600 hoặc responsive hẹp (~120–160px).',
    'chapter_reader',
    '/truyen/*/chuong/*',
    'desktop',
    'sidebar',
    'display',
    'responsive',
    160,
    600,
    160,
    600,
    false,
    true,
    1,
    0,
    true,
    true,
    'reader_ads',
    'Hiển thị từ xl (≥1280px), sticky khi cuộn.'
  )
on conflict (placement_key) do nothing;
