/**
 * Generates supabase/migrations/161_taxonomy_seed.sql from lib/taxonomy/seed/default-terms.ts
 * Run: npx --yes tsx scripts/generate-taxonomy-seed-sql.ts
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  DEFAULT_STORY_FORMAT_TEMPLATE_SEEDS,
  DEFAULT_TAXONOMY_SEED_TERMS
} from "../lib/taxonomy/seed/default-terms";
import { SUBGENRE_PARENT_SLUG_BY_SUBGENRE_SLUG } from "../lib/taxonomy/seed/subgenre-parents";

function sqlString(value: string) {
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlBool(value: boolean | undefined, fallback: boolean) {
  return (value ?? fallback) ? "true" : "false";
}

const termRows = DEFAULT_TAXONOMY_SEED_TERMS.map((term) => {
  const aliases =
    term.aliases && term.aliases.length > 0
      ? `'${JSON.stringify(term.aliases).replace(/'/g, "''")}'::jsonb`
      : "'[]'::jsonb";

  return `  (${sqlString(term.type)}, ${sqlString(term.slug)}, ${sqlString(term.name)}, ${term.sortOrder ?? 0}, ${sqlBool(term.isSelectableByCreator, true)}, ${sqlBool(term.isPublic, true)}, ${sqlBool(term.isActive, true)}, ${sqlBool(term.isFeatured, false)}, ${sqlBool(term.useForModeration, term.type === "editorial_tag")}, ${aliases})`;
});

const templateRows = DEFAULT_STORY_FORMAT_TEMPLATE_SEEDS.map(
  (tpl) =>
    `  (${sqlString(tpl.mode)}, ${sqlString(tpl.name)}, ${sqlString(tpl.description)}, ${sqlBool(tpl.isDefault, false)}, ${tpl.sortOrder})`
);

function buildSubgenreParentPatchSql() {
  const cases = Object.entries(SUBGENRE_PARENT_SLUG_BY_SUBGENRE_SLUG)
    .map(
      ([childSlug, parentSlug]) =>
        `    when ${sqlString(childSlug)} then ${sqlString(parentSlug)}`
    )
    .join("\n");

  return `
-- Link subgenre → main_genre (parent_id)
update public.taxonomy_terms child
set parent_id = parent.id, updated_at = now()
from public.taxonomy_terms parent
where child.type = 'subgenre'
  and parent.type = 'main_genre'
  and child.parent_id is null
  and parent.slug = case child.slug
${cases}
    else null
  end
  and parent.slug is not null;
`;
}

const sql = `-- Migration 161: Default taxonomy terms and presentation format templates
-- Generated by scripts/generate-taxonomy-seed-sql.ts — do not hand-edit term list; edit lib/taxonomy/seed/default-terms.ts

insert into public.taxonomy_terms (
  type,
  slug,
  name,
  sort_order,
  is_selectable_by_creator,
  is_public,
  is_active,
  is_featured,
  use_for_moderation,
  aliases
)
select v.type, v.slug, v.name, v.sort_order, v.is_selectable_by_creator, v.is_public, v.is_active, v.is_featured, v.use_for_moderation, v.aliases
from (
  values
${termRows.join(",\n")}
) as v(type, slug, name, sort_order, is_selectable_by_creator, is_public, is_active, is_featured, use_for_moderation, aliases)
on conflict (type, slug) do update set
  name = excluded.name,
  sort_order = excluded.sort_order,
  is_selectable_by_creator = excluded.is_selectable_by_creator,
  is_public = excluded.is_public,
  is_active = excluded.is_active,
  is_featured = excluded.is_featured,
  use_for_moderation = excluded.use_for_moderation,
  aliases = excluded.aliases,
  updated_at = now();

insert into public.story_format_templates (
  mode,
  name,
  description,
  is_default,
  sort_order,
  is_active
)
select v.mode, v.name, v.description, v.is_default, v.sort_order, true
from (
  values
${templateRows.join(",\n")}
) as v(mode, name, description, is_default, sort_order)
on conflict (mode, name) do update set
  description = excluded.description,
  is_default = excluded.is_default,
  sort_order = excluded.sort_order,
  is_active = true,
  updated_at = now();

${buildSubgenreParentPatchSql()}
`;

const outPath = join(
  process.cwd(),
  "supabase",
  "migrations",
  "161_taxonomy_seed.sql"
);
writeFileSync(outPath, sql, "utf8");
console.log(`Wrote ${outPath} (${DEFAULT_TAXONOMY_SEED_TERMS.length} taxonomy terms)`);
